name: Publish to S3

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          node_version: 20.x

      - name: Test
        run: pnpm run test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Configuring OpenID Connect in AWS, change the role-to-assume to your role ARN
          role-to-assume: YOUR-ROLE-ARN-TO-ASSUME
          aws-region: ap-northeast-1

      - name: Sync dist folder to S3
        # Change YOUR-S3-BUCKET-NAME to your S3 bucket name that you want to deploy
        run: |
          aws s3 sync dist s3://YOUR-S3-BUCKET-NAME --delete

      - name: Invalidate CloudFront cache
        # change YOUR-DISTRIBUTION-ID to your CloudFront distribution ID to invalidate the cache
        run: |
          aws cloudfront create-invalidation --distribution-id YOUR-DISTRIBUTION-ID --paths "/*"
